In [1]:
import openpyxl
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter
import pandas as pd
import numpy as np
import re

In [2]:
wb = load_workbook(r"C:\Users\nsyrymbet\Desktop\SEB доли W49.xlsx")
ws = wb.active

for i in range(1,7):
        ws.delete_rows(1)
        
wb.save(r"C:\Users\nsyrymbet\Desktop\SEB доли.xlsx")

In [3]:
df = pd.read_excel(r"C:\Users\nsyrymbet\Desktop\SEB доли.xlsx", header = None)
df

,0,1,2,3,4,5,6,7,8,9,...,312,313,314,315,316,317,318,319,320,321
0,Номенклатура номенклатурная группа,NaN,NaN,Итого,NaN,"Абай пр-т. Победы, стр. 7",NaN,NaN,"Айтеке Би, ул. Айтеке Би, д. 48 «Казалинск»",NaN,...,"Шымкент, мкр-н Нурсат, зд. 121А",NaN,"Шымкент, ул. Жиделибайсын, зд. 92",NaN,"Шымкент, ул. Уалиханова, д. 198",NaN,Экибастуз www.mechta.kz,NaN,Экибастуз М. Жусупа 88,NaN
1,NaN,NaN,NaN,Итоговый процент количество,Итоговый процент сумма,Общий процент количество,Общий процент сумма,NaN,Общий процент количество,Общий процент сумма,...,Общий процент количество,Общий процент сумма,Общий процент количество,Общий процент сумма,Общий процент количество,Общий процент сумма,Общий процент количество,Общий процент сумма,Общий процент количество,Общий процент сумма
2,Аксессуар для вафель,NaN,NaN,100,100,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Бутербродница,NaN,NaN,12.5,49.91,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Вентилятор,NaN,NaN,16.67,58.71,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,Чайник,NaN,NaN,12.5,11.88,NaN,NaN,NaN,NaN,NaN,...,33.33,32.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Щипцы,NaN,NaN,6.9,42.91,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Электропечь,NaN,NaN,1.09,2.67,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Электрочайник,NaN,NaN,13.64,24.28,NaN,NaN,NaN,NaN,NaN,...,28.57,46.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Итого,NaN,NaN,19.29,26.17,60,58.77,NaN,38.89,50.02,...,42.86,50.68,34.04,26.86,40,47.55,NaN,NaN,50,65.16

In [4]:
df = df.drop(df.columns[[1,2,7]], axis = 1)
df

# df = df.drop(df.columns[[1,2]], axis = 1)
# df

,0,3,4,5,6,8,9,10,11,12,...,312,313,314,315,316,317,318,319,320,321
0,Номенклатура номенклатурная группа,Итого,NaN,"Абай пр-т. Победы, стр. 7",NaN,"Айтеке Би, ул. Айтеке Би, д. 48 «Казалинск»",NaN,Аксай www.mechta.kz,NaN,"Аксай, мкр-н 5А, д. 6А",...,"Шымкент, мкр-н Нурсат, зд. 121А",NaN,"Шымкент, ул. Жиделибайсын, зд. 92",NaN,"Шымкент, ул. Уалиханова, д. 198",NaN,Экибастуз www.mechta.kz,NaN,Экибастуз М. Жусупа 88,NaN
1,NaN,Итоговый процент количество,Итоговый процент сумма,Общий процент количество,Общий процент сумма,Общий процент количество,Общий процент сумма,Общий процент количество,Общий процент сумма,Общий процент количество,...,Общий процент количество,Общий процент сумма,Общий процент количество,Общий процент сумма,Общий процент количество,Общий процент сумма,Общий процент количество,Общий процент сумма,Общий процент количество,Общий процент сумма
2,Аксессуар для вафель,100,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Бутербродница,12.5,49.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Вентилятор,16.67,58.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,Чайник,12.5,11.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.33,32.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Щипцы,6.9,42.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Электропечь,1.09,2.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Электрочайник,13.64,24.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28.57,46.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Итого,19.29,26.17,60,58.77,38.89,50.02,100,100,100,...,42.86,50.68,34.04,26.86,40,47.55,NaN,NaN,50,65.16

In [5]:
df = df.T
df

,0,1,2,3,4,5,6,7,8,9,...,60,61,62,63,64,65,66,67,68,69
0,Номенклатура номенклатурная группа,NaN,Аксессуар для вафель,Бутербродница,Вентилятор,Венчик,Вертикальный пылесос,Весы,Гладильная доска,Гладильная система,...,Фен,Фен плойка,Фильтр (для пылесоса),Фильтр для очистки воды в кофемашинах,Хлебопечь,Чайник,Щипцы,Электропечь,Электрочайник,Итого
3,Итого,Итоговый процент количество,100,12.5,16.67,16.22,11.01,17.13,10.32,48.44,...,41.51,46.83,0.73,7.69,10,12.5,6.9,1.09,13.64,19.29
4,NaN,Итоговый процент сумма,100,49.91,58.71,16,23.93,22.95,30.11,43.33,...,55.07,64.48,0.74,16.3,8.6,11.88,42.91,2.67,24.28,26.17
5,"Абай пр-т. Победы, стр. 7",Общий процент количество,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60
6,NaN,Общий процент сумма,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,NaN,Общий процент сумма,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,39.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.55
318,Экибастуз www.mechta.kz,Общий процент количество,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,NaN,Общий процент сумма,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,Экибастуз М. Жусупа 88,Общий процент количество,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50
321,NaN,Общий процент сумма,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,38.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.16

In [6]:
df = df.rename(columns=df.iloc[0])

df.rename(columns={df.columns[0]:'Sales'}, inplace=True)
df.rename(columns={df.columns[1]:'Shops'}, inplace=True)

df = df.drop(df.index[0])

df['Sales'] = df['Sales'].fillna(method='ffill')
df = df.reset_index(drop = True)


df

,Sales,Shops,Аксессуар для вафель,Бутербродница,Вентилятор,Венчик,Вертикальный пылесос,Весы,Гладильная доска,Гладильная система,...,Фен,Фен плойка,Фильтр (для пылесоса),Фильтр для очистки воды в кофемашинах,Хлебопечь,Чайник,Щипцы,Электропечь,Электрочайник,Итого
0,Итого,Итоговый процент количество,100,12.5,16.67,16.22,11.01,17.13,10.32,48.44,...,41.51,46.83,0.73,7.69,10,12.5,6.9,1.09,13.64,19.29
1,Итого,Итоговый процент сумма,100,49.91,58.71,16,23.93,22.95,30.11,43.33,...,55.07,64.48,0.74,16.3,8.6,11.88,42.91,2.67,24.28,26.17
2,"Абай пр-т. Победы, стр. 7",Общий процент количество,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60
3,"Абай пр-т. Победы, стр. 7",Общий процент сумма,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.77
4,"Айтеке Би, ул. Айтеке Би, д. 48 «Казалинск»",Общий процент количество,NaN,NaN,NaN,NaN,NaN,50,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,"Шымкент, ул. Уалиханова, д. 198",Общий процент сумма,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,39.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.55
314,Экибастуз www.mechta.kz,Общий процент количество,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,Экибастуз www.mechta.kz,Общий процент сумма,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,Экибастуз М. Жусупа 88,Общий процент количество,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50
317,Экибастуз М. Жусупа 88,Общий процент сумма,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,38.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.16

In [7]:
unpivoted_df = pd.melt(df, id_vars=['Sales', 'Shops'], var_name='Category', value_name='Value')
unpivoted_df = unpivoted_df.dropna()
unpivoted_df = unpivoted_df.drop_duplicates()
unpivoted_df = unpivoted_df[unpivoted_df['Value'] != 0]
unpivoted_df = unpivoted_df[unpivoted_df['Value'] != '#DIV/0']
unpivoted_df

,Sales,Shops,Category,Value
0,Итого,Итоговый процент количество,Аксессуар для вафель,100
1,Итого,Итоговый процент сумма,Аксессуар для вафель,100
112,"Астана, ул. Амман, д. 14",Общий процент количество,Аксессуар для вафель,100
113,"Астана, ул. Амман, д. 14",Общий процент сумма,Аксессуар для вафель,100
188,"Караганда, пр-т Бухар Жырау, д. 76",Общий процент количество,Аксессуар для вафель,100
...,...,...,...,...
21617,"Шымкент, ул. Жиделибайсын, зд. 92",Общий процент сумма,Итого,26.86
21618,"Шымкент, ул. Уалиханова, д. 198",Общий процент количество,Итого,40
21619,"Шымкент, ул. Уалиханова, д. 198",Общий процент сумма,Итого,47.55
21622,Экибастуз М. Жусупа 88,Общий процент количество,Итого,50
21623,Экибастуз М. Жусупа 88,Общий процент сумма,Итого,65.16

In [8]:
pivot = pd.pivot_table(unpivoted_df, values='Value', 
                                index=['Sales', 'Category'], 
                                columns='Shops', 
                                aggfunc=np.mean)
pivot

Shops                                                                    Итоговый процент количество  \
Sales                                        Category
Абай пр-т. Победы, стр. 7                    Итого                                               NaN
                                             Отпариватель электрический                          NaN
                                             Ручной блендер                                      NaN
Айтеке Би, ул. Айтеке Би, д. 48  «Казалинск» Весы                                                NaN
                                             Итого                                               NaN
...                                                                                              ...
Экибастуз М. Жусупа 88                       Мясорубка                                           NaN
                                             Настольный гриль                                    NaN
                                             Триммер для волос                                   NaN
                                             Утюг                                                NaN
                                             Фен                                                 NaN

Shops                                                                    Итоговый процент сумма  \
Sales                                        Category
Абай пр-т. Победы, стр. 7                    Итого                                          NaN
                                             Отпариватель электрический                     NaN
                                             Ручной блендер                                 NaN
Айтеке Би, ул. Айтеке Би, д. 48  «Казалинск» Весы                                           NaN
                                             Итого                                          NaN
...                                                                                         ...
Экибастуз М. Жусупа 88                       Мясорубка                                      NaN
                                             Настольный гриль                               NaN
                                             Триммер для волос                              NaN
                                             Утюг                                           NaN
                                             Фен                                            NaN

Shops                                                                    Общий процент количество  \
Sales                                        Category
Абай пр-т. Победы, стр. 7                    Итого                                          60.00
                                             Отпариватель электрический                     50.00
                                             Ручной блендер                                 66.67
Айтеке Би, ул. Айтеке Би, д. 48  «Казалинск» Весы                                           50.00
                                             Итого                                          38.89
...                                                                                           ...
Экибастуз М. Жусупа 88                       Мясорубка                                      63.64
                                             Настольный гриль                              100.00
                                             Триммер для волос                              50.00
                                             Утюг                                           25.00
                                             Фен                                            40.00

Shops                                                                    Общий процент сумма
Sales                                        Category
Абай пр-т. Победы, стр. 7                    Итого                                     58.77
                                             Отпариватель электрический                54.57
                                             Ручной блендер                            67.81
Айтеке Би, ул. Айтеке Би, д. 48  «Казалинск» Весы                                      61.79
                                             Итого                                     50.02
...                                                                                      ...
Экибастуз М. Жусупа 88                       Мясорубка                                 70.02
                                             Настольный гриль                         100.00
                                             Триммер для волос                         68.17
                                             Утюг                                      34.68
                                             Фен                                       38.95

[1337 rows x 4 columns]

In [9]:
pivot = pivot.reset_index()
pivot['Sales'] = pivot['Sales'].fillna(method='ffill')
pivot = pivot.reset_index()
pivot

Shops,index,Sales,Category,Итоговый процент количество,Итоговый процент сумма,Общий процент количество,Общий процент сумма
0,0,"Абай пр-т. Победы, стр. 7",Итого,NaN,NaN,60.00,58.77
1,1,"Абай пр-т. Победы, стр. 7",Отпариватель электрический,NaN,NaN,50.00,54.57
2,2,"Абай пр-т. Победы, стр. 7",Ручной блендер,NaN,NaN,66.67,67.81
3,3,"Айтеке Би, ул. Айтеке Би, д. 48 «Казалинск»",Весы,NaN,NaN,50.00,61.79
4,4,"Айтеке Би, ул. Айтеке Би, д. 48 «Казалинск»",Итого,NaN,NaN,38.89,50.02
...,...,...,...,...,...,...,...
1332,1332,Экибастуз М. Жусупа 88,Мясорубка,NaN,NaN,63.64,70.02
1333,1333,Экибастуз М. Жусупа 88,Настольный гриль,NaN,NaN,100.00,100.00
1334,1334,Экибастуз М. Жусупа 88,Триммер для волос,NaN,NaN,50.00,68.17
1335,1335,Экибастуз М. Жусупа 88,Утюг,NaN,NaN,25.00,34.68
1336,1336,Экибастуз М. Жусупа 88,Фен,NaN,NaN,40.00,38.95

In [10]:
pivot_without_sums = pivot[(pivot['Category'] != 'Итого') & (pivot['Sales'] != 'Итого')]
pivot_without_sums = pivot_without_sums[['Sales', 'Category', 'Общий процент количество', 'Общий процент сумма']]
pivot_without_sums.rename(columns={'Общий процент количество': 'шт', 'Общий процент сумма': 'тг'}, inplace=True)
pivot_without_sums

Shops,Sales,Category,шт,тг
1,"Абай пр-т. Победы, стр. 7",Отпариватель электрический,50.00,54.57
2,"Абай пр-т. Победы, стр. 7",Ручной блендер,66.67,67.81
3,"Айтеке Би, ул. Айтеке Би, д. 48 «Казалинск»",Весы,50.00,61.79
5,"Айтеке Би, ул. Айтеке Би, д. 48 «Казалинск»",Мясорубка,66.67,78.01
6,"Айтеке Би, ул. Айтеке Би, д. 48 «Казалинск»",Прибор для распрямления волос,40.00,60.05
...,...,...,...,...
1332,Экибастуз М. Жусупа 88,Мясорубка,63.64,70.02
1333,Экибастуз М. Жусупа 88,Настольный гриль,100.00,100.00
1334,Экибастуз М. Жусупа 88,Триммер для волос,50.00,68.17
1335,Экибастуз М. Жусупа 88,Утюг,25.00,34.68
1336,Экибастуз М. Жусупа 88,Фен,40.00,38.95

In [11]:
pivot_with_sums = pivot[(pivot['Category'] == 'Итого') & (pivot['Sales'] != 'Итого')]
pivot_with_sums = pivot_with_sums.replace('Итого', 'Итог по  магазину')
pivot_with_sums = pivot_with_sums[['Sales', 'Category', 'Общий процент количество', 'Общий процент сумма']]
pivot_with_sums.rename(columns={'Общий процент количество': 'шт', 'Общий процент сумма': 'тг'}, inplace=True)
pivot_with_sums

Shops,Sales,Category,шт,тг
0,"Абай пр-т. Победы, стр. 7",Итог по магазину,60.00,58.77
4,"Айтеке Би, ул. Айтеке Би, д. 48 «Казалинск»",Итог по магазину,38.89,50.02
9,Аксай www.mechta.kz,Итог по магазину,100.00,100.00
11,"Аксай, мкр-н 5А, д. 6А",Итог по магазину,100.00,100.00
14,"Аксу, ул. Камзина, уч. 31/2",Итог по магазину,33.33,-21.43
...,...,...,...,...
1290,Шымкент www.mechta.kz,Итог по магазину,87.50,91.27
1296,"Шымкент, мкр-н Нурсат, зд. 121А",Итог по магазину,42.86,50.68
1310,"Шымкент, ул. Жиделибайсын, зд. 92",Итог по магазину,34.04,26.86
1321,"Шымкент, ул. Уалиханова, д. 198",Итог по магазину,40.00,47.55
1331,Экибастуз М. Жусупа 88,Итог по магазину,50.00,65.16

In [12]:
more = pivot[(pivot['Sales'] == 'Итого')]
more = more.replace('Итого', 'Итоги катег-ии')
more.loc[more['Category'] == 'Общий итог', 'Sales'] = 'Общий итог'
more = more[['Sales', 'Category', 'Итоговый процент количество', 'Итоговый процент сумма']]
more.rename(columns={'Итоговый процент количество': 'шт', 'Итоговый процент сумма': 'тг'}, inplace=True)
more

Shops           Sales              Category      шт      тг
725    Итоги катег-ии  Аксессуар для вафель  100.00  100.00
726    Итоги катег-ии         Бутербродница   12.50   49.91
727    Итоги катег-ии            Вентилятор   16.67   58.71
728    Итоги катег-ии                Венчик   16.22   16.00
729    Итоги катег-ии  Вертикальный пылесос   11.01   23.93
..                ...                   ...     ...     ...
788    Итоги катег-ии             Хлебопечь   10.00    8.60
789    Итоги катег-ии                Чайник   12.50   11.88
790    Итоги катег-ии                 Щипцы    6.90   42.91
791    Итоги катег-ии           Электропечь    1.09    2.67
792    Итоги катег-ии         Электрочайник   13.64   24.28

[68 rows x 4 columns]

In [13]:
final = pivot_without_sums.append([pivot_with_sums, more]).reset_index(drop=True)
final = final.drop_duplicates()
final['шт'] = final['шт'] /100
final['тг'] = final['тг'] /100

final

C:\Users\nsyrymbet\AppData\Local\Temp\ipykernel_17036\2049659426.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final = pivot_without_sums.append([pivot_with_sums, more]).reset_index(drop=True)

Shops,Sales,Category,шт,тг
0,"Абай пр-т. Победы, стр. 7",Отпариватель электрический,0.5000,0.5457
1,"Абай пр-т. Победы, стр. 7",Ручной блендер,0.6667,0.6781
2,"Айтеке Би, ул. Айтеке Би, д. 48 «Казалинск»",Весы,0.5000,0.6179
3,"Айтеке Би, ул. Айтеке Би, д. 48 «Казалинск»",Мясорубка,0.6667,0.7801
4,"Айтеке Би, ул. Айтеке Би, д. 48 «Казалинск»",Прибор для распрямления волос,0.4000,0.6005
...,...,...,...,...
1332,Итоги катег-ии,Хлебопечь,0.1000,0.0860
1333,Итоги катег-ии,Чайник,0.1250,0.1188
1334,Итоги катег-ии,Щипцы,0.0690,0.4291
1335,Итоги катег-ии,Электропечь,0.0109,0.0267
1336,Итоги катег-ии,Электрочайник,0.1364,0.2428

In [14]:
final.to_excel(r"C:\Users\nsyrymbet\Desktop\shares me.xlsx", index=False)